// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: goklipper/internal/pkg/filament/ace_v2/ace_proto_v2.proto

package ace_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetFanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speed         uint32                 `protobuf:"varint,1,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFanRequest) Reset() {
	*x = SetFanRequest{}
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFanRequest) ProtoMessage() {}

func (x *SetFanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFanRequest.ProtoReflect.Descriptor instead.
func (*SetFanRequest) Descriptor() ([]byte, []int) {
	return file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescGZIP(), []int{0}
}

func (x *SetFanRequest) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type SetRfidEnableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRfidEnableRequest) Reset() {
	*x = SetRfidEnableRequest{}
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRfidEnableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRfidEnableRequest) ProtoMessage() {}

func (x *SetRfidEnableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRfidEnableRequest.ProtoReflect.Descriptor instead.
func (*SetRfidEnableRequest) Descriptor() ([]byte, []int) {
	return file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescGZIP(), []int{1}
}

func (x *SetRfidEnableRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type DryingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   uint32                 `protobuf:"varint,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	DurationHours uint32                 `protobuf:"varint,2,opt,name=duration_hours,json=durationHours,proto3" json:"duration_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DryingRequest) Reset() {
	*x = DryingRequest{}
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DryingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DryingRequest) ProtoMessage() {}

func (x *DryingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DryingRequest.ProtoReflect.Descriptor instead.
func (*DryingRequest) Descriptor() ([]byte, []int) {
	return file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescGZIP(), []int{2}
}

func (x *DryingRequest) GetTemperature() uint32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *DryingRequest) GetDurationHours() uint32 {
	if x != nil {
		return x.DurationHours
	}
	return 0
}

type FeedOrRollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Speed         uint32                 `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedOrRollbackRequest) Reset() {
	*x = FeedOrRollbackRequest{}
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedOrRollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedOrRollbackRequest) ProtoMessage() {}

func (x *FeedOrRollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedOrRollbackRequest.ProtoReflect.Descriptor instead.
func (*FeedOrRollbackRequest) Descriptor() ([]byte, []int) {
	return file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescGZIP(), []int{3}
}

func (x *FeedOrRollbackRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FeedOrRollbackRequest) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type FilamentInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotIndex     uint32                 `protobuf:"varint,1,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	ColorHex      string                 `protobuf:"bytes,2,opt,name=color_hex,json=colorHex,proto3" json:"color_hex,omitempty"`
	CurrentTemp   uint32                 `protobuf:"varint,3,opt,name=current_temp,json=currentTemp,proto3" json:"current_temp,omitempty"`
	IsDrying      bool                   `protobuf:"varint,4,opt,name=is_drying,json=isDrying,proto3" json:"is_drying,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilamentInfoResponse) Reset() {
	*x = FilamentInfoResponse{}
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilamentInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilamentInfoResponse) ProtoMessage() {}

func (x *FilamentInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilamentInfoResponse.ProtoReflect.Descriptor instead.
func (*FilamentInfoResponse) Descriptor() ([]byte, []int) {
	return file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescGZIP(), []int{4}
}

func (x *FilamentInfoResponse) GetSlotIndex() uint32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *FilamentInfoResponse) GetColorHex() string {
	if x != nil {
		return x.ColorHex
	}
	return ""
}

func (x *FilamentInfoResponse) GetCurrentTemp() uint32 {
	if x != nil {
		return x.CurrentTemp
	}
	return 0
}

func (x *FilamentInfoResponse) GetIsDrying() bool {
	if x != nil {
		return x.IsDrying
	}
	return false
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         uint32                 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	CurrentTemp   uint32                 `protobuf:"varint,2,opt,name=current_temp,json=currentTemp,proto3" json:"current_temp,omitempty"`
	TargetTemp    uint32                 `protobuf:"varint,3,opt,name=target_temp,json=targetTemp,proto3" json:"target_temp,omitempty"`
	ErrorFlag     bool                   `protobuf:"varint,4,opt,name=error_flag,json=errorFlag,proto3" json:"error_flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *StatusResponse) GetCurrentTemp() uint32 {
	if x != nil {
		return x.CurrentTemp
	}
	return 0
}

func (x *StatusResponse) GetTargetTemp() uint32 {
	if x != nil {
		return x.TargetTemp
	}
	return 0
}

func (x *StatusResponse) GetErrorFlag() bool {
	if x != nil {
		return x.ErrorFlag
	}
	return false
}

var File_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto protoreflect.FileDescriptor

const file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDesc = "" +
	"\n" +
	"3goklipper/internal/pkg/filament/ace_v2/ace_proto_v2.proto\x12\x06ace_v2\"%\n" +
	"\rSetFanRequest\x12\x14\n" +
	"\x05speed\x18\x01 \x01(\rR\x05speed\".\n" +
	"\x14SetRfidEnableRequest\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\"X\n" +
	"\rDryingRequest\x12 \n" +
	"\vtemperature\x18\x01 \x01(\rR\vtemperature\x12%\n" +
	"\x0eduration_hours\x18\x02 \x01(\rR\rdurationHours\"E\n" +
	"\x15FeedOrRollbackRequest\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\rR\x05speed\"\x92\x01\n" +
	"\x14FilamentInfoResponse\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x01 \x01(\rR\tslotIndex\x12\x1b\n" +
	"\tcolor_hex\x18\x02 \x01(\tR\bcolorHex\x12!\n" +
	"\fcurrent_temp\x18\x03 \x01(\rR\vcurrentTemp\x12\x1b\n" +
	"\tis_drying\x18\x04 \x01(\bR\bisDrying\"\x89\x01\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\rR\x05state\x12!\n" +
	"\fcurrent_temp\x18\x02 \x01(\rR\vcurrentTemp\x12\x1f\n" +
	"\vtarget_temp\x18\x03 \x01(\rR\n" +
	"targetTemp\x12\x1d\n" +
	"\n" +
	"error_flag\x18\x04 \x01(\bR\terrorFlagB\"Z goklipper/internal/pkg/filament/ace_v2b\x06proto3"

var (
	file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescOnce sync.Once
	file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescData []byte
)

func file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescGZIP() []byte {
	file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescOnce.Do(func() {
		file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDesc), len(file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDesc)))
	})
	return file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDescData
}

var file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_goTypes = []any{
	(*SetFanRequest)(nil),         // 0: ace_v2.SetFanRequest
	(*SetRfidEnableRequest)(nil),  // 1: ace_v2.SetRfidEnableRequest
	(*DryingRequest)(nil),         // 2: ace_v2.DryingRequest
	(*FeedOrRollbackRequest)(nil), // 3: ace_v2.FeedOrRollbackRequest
	(*FilamentInfoResponse)(nil),  // 4: ace_v2.FilamentInfoResponse
	(*StatusResponse)(nil),        // 5: ace_v2.StatusResponse
}
var file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_init() }
func file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_init() {
	if File_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDesc), len(file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_goTypes,
		DependencyIndexes: file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_depIdxs,
		MessageInfos:      file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_msgTypes,
	}.Build()
	File_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto = out.File
	file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_goTypes = nil
	file_goklipper_internal_pkg_filament_ace_v2_ace_proto_v2_proto_depIdxs = nil
}
