//go:build chelper_embed
// +build chelper_embed

#include "../../../chelper/itersolve.c"
#include "../../../chelper/kin_cartesian.c"
#include "../../../chelper/kin_corexy.c"
#include "../../../chelper/kin_corexz.c"
#include "../../../chelper/kin_delta.c"
#include "../../../chelper/kin_deltesian.c"
#include "../../../chelper/kin_extruder.c"
#include "../../../chelper/kin_polar.c"
#include "../../../chelper/kin_rotary_delta.c"
#include "../../../chelper/kin_shaper.c"
#include "../../../chelper/kin_winch.c"
#include "../../../chelper/msgblock.c"
#include "../../../chelper/pollreactor.c"
#include "../../../chelper/pyhelper.c"
#include "../../../chelper/serialqueue.c"
#include "../../../chelper/stepcompress.c"
#include "../../../chelper/trapq.c"
#include "../../../chelper/trdispatch.c"
